sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

language: node_js
node_js:
  - "node"
  - "7"

before_script:
  - npm install -g @angular/cli@latest
  - npm install
  - npm update

script:
    - ng build --prod
